name: C build

on:
  push:

jobs:
  make_check:
    strategy:
      matrix:
        os:
        - macOS-latest
        - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ConorMacBride/install-package@v1
        with:
          # Note: aclocal is packaged with automake in Homebrew, so we need it
          # even though we don't use automake.
          brew: autoconf automake popt python python3 python-setuptools
          # Note: no gdb on macOS because it's apparently not supported on arm64
          apt: clang libavahi-client-dev libpopt-dev gdb python3-dev python3-setuptools
          # brew-cask: TODO
          # choco: TODO
      - run: which python3
      - run: ./autogen.sh
      # Setting `python3` helps it find the Homebrew Python on macOS.
      - run: ./configure PYTHON=python3
      - run: make
      - run: make check
